{% set name = "wagtail" %}
{% set version = "6.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wagtail-{{ version }}.tar.gz
  sha256: e7cfc3c0f53fb302f1798f0e02a7ac6078ab02eb0e8703c0f71ccbd3f18e386f

build:
  entry_points:
    - wagtail = wagtail.bin.wagtail:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - django >=4.2,<6.0
    - django-modelcluster >=6.2.1,<7.0
    - django-permissionedforms >=0.1,<1.0
    - django-taggit >=4.0,<5.1
    - django-treebeard >=4.5.1,<5.0
    - djangorestframework >=3.15.1,<4.0
    - django-filter >=23.3,<24
    - draftjs_exporter >=2.1.5,<6.0
    - pillow >=9.1.0,<11.0.0
    - beautifulsoup4 >=4.8,<4.13
    - html5lib >=0.999,<2
    - willow >=1.8.0,<2
    - requests >=2.11.1,<3.0
    - l18n >=2018.5
    - openpyxl >=3.0.10,<4.0
    - anyascii >=0.1.5
    - telepath >=0.3.1,<1
    - laces >=0.1,<0.2

test:
  imports:
    - wagtail
  commands:
    - pip check
    - wagtail help
  requires:
    - pip

about:
  home: https://github.com/wagtail/wagtail
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A Django content management system focused on flexibility and user experience '
  description: |
    Wagtail is an open source content management system built on Django, with a strong community and commercial support.
    It's focused on user experience, and offers precise control for designers and developers.
  doc_url: https://docs.wagtail.org/en/stable/
  dev_url: https://github.com/wagtail/wagtail

extra:
  recipe-maintainers:
    - darynwhite
    - rxm7706
