{% set name = "wagtail" %}
{% set version = "2.4" %}
{% set sha256 = "1dd069ef8b3a08728fa5304e45ee2a92ed49b8e235e9c8b677adfd2039cff1fd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - wagtail=wagtail.bin.wagtail:main

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - django >=1.11,<2.2
    - django-modelcluster >=4.2,<5.0
    - django-taggit >=0.23,<0.24
    - django-treebeard >=4.2.0,<5.0
    - djangorestframework >=3.7.4,<4.0
    - draftjs_exporter >=2.1.5,<3.0
    - pillow >=4.0.0,<6.0
    - beautifulsoup4 >=4.5.1,<4.6.1
    - html5lib >=0.999,<2
    - unidecode >=0.04.14,<2.0
    - willow >=1.1,<1.2
    - requests >=2.11.1,<3.0
    - pytz>=2016.6
    - six>=1.11,<2.0
   
test:
  commands:
    - wagtail help

about:
  home: https://github.com/wagtail/wagtail
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A Django content management system focused on flexibility and user experience '
  description: |
    Wagtail is a content management system built on Django. It's focused on user experience, 
    and offers precise control for designers and developers.
  doc_url: http://docs.wagtail.io/en/v2.0/
  dev_url: https://github.com/wagtail/wagtail

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
