import django
from django.conf import settings
settings.configure(INSTALLED_APPS=['wagtail', 'django.contrib.contenttypes', 'django.contrib.auth']) 
django.setup() 

import wagtail
import wagtail.snippets
import wagtail.snippets.views
import wagtail.core
import wagtail.core.blocks
import wagtail.core.templatetags
import wagtail.core.migrations
import wagtail.core.permission_policies
import wagtail.core.tests
import wagtail.core.management
import wagtail.core.management.commands
import wagtail.core.rich_text
import wagtail.bin
import wagtail.images
import wagtail.images.templatetags
import wagtail.images.migrations
import wagtail.images.tests
import wagtail.images.api
import wagtail.images.api.admin
import wagtail.images.api.v2
import wagtail.images.views
import wagtail.tests
import wagtail.tests.snippets
import wagtail.tests.snippets.migrations
import wagtail.tests.customuser
import wagtail.tests.customuser.migrations
import wagtail.tests.testapp
import wagtail.tests.testapp.migrations
import wagtail.tests.modeladmintest
import wagtail.tests.modeladmintest.migrations
import wagtail.tests.routablepage
import wagtail.tests.routablepage.migrations
import wagtail.tests.utils
import wagtail.tests.demosite
import wagtail.tests.demosite.migrations
import wagtail.tests.search
import wagtail.tests.search.migrations
import wagtail.admin
import wagtail.admin.templatetags
import wagtail.admin.migrations
import wagtail.admin.viewsets
import wagtail.admin.tests
import wagtail.admin.tests.api
import wagtail.admin.urls
import wagtail.admin.api
import wagtail.admin.rich_text
import wagtail.admin.rich_text.editors
import wagtail.admin.rich_text.editors.draftail
import wagtail.admin.rich_text.converters
import wagtail.admin.views
import wagtail.utils
import wagtail.contrib
import wagtail.contrib.settings
import wagtail.contrib.settings.templatetags
import wagtail.contrib.settings.tests
import wagtail.contrib.frontend_cache
import wagtail.contrib.routable_page
import wagtail.contrib.routable_page.templatetags
import wagtail.contrib.forms
import wagtail.contrib.forms.migrations
import wagtail.contrib.forms.tests
import wagtail.contrib.search_promotions
import wagtail.contrib.search_promotions.templatetags
import wagtail.contrib.search_promotions.migrations
import wagtail.contrib.table_block
import wagtail.contrib.styleguide
import wagtail.contrib.redirects
import wagtail.contrib.redirects.migrations
import wagtail.contrib.modeladmin
import wagtail.contrib.modeladmin.templatetags
import wagtail.contrib.modeladmin.tests
import wagtail.contrib.modeladmin.helpers
import wagtail.contrib.sitemaps
import wagtail.contrib.postgres_search
import wagtail.contrib.postgres_search.migrations
import wagtail.contrib.postgres_search.tests
import wagtail.search
import wagtail.search.migrations
import wagtail.search.backends
import wagtail.search.tests
import wagtail.search.management
import wagtail.search.management.commands
import wagtail.search.urls
import wagtail.search.views
import wagtail.sites
import wagtail.project_template.home
import wagtail.project_template.home.migrations
import wagtail.project_template.project_name
import wagtail.project_template.project_name.settings
import wagtail.project_template.search
import wagtail.users
import wagtail.users.templatetags
import wagtail.users.migrations
import wagtail.users.urls
import wagtail.users.views
import wagtail.api
import wagtail.api.v2
import wagtail.api.v2.tests
import wagtail.documents
import wagtail.documents.migrations
import wagtail.documents.tests
import wagtail.documents.api
import wagtail.documents.api.admin
import wagtail.documents.api.v2
import wagtail.documents.views
import wagtail.embeds
import wagtail.embeds.templatetags
import wagtail.embeds.migrations
import wagtail.embeds.finders
import wagtail.embeds.views
